# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('theme_verse', models.CharField(max_length=100)),
                ('verse', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=300)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
