# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('box', models.CharField(max_length=2000)),
                ('location', models.CharField(max_length=1000)),
                ('notesadd', models.CharField(max_length=300)),
                ('notescont', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('is_prayer_request', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=2000)),
            ],
        ),
    ]
