# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='men',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='women',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='youth',
            name='content',
            field=models.TextField(),
        ),
    ]
