# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('verse', models.CharField(max_length=1000)),
                ('principle', models.CharField(max_length=1000)),
                ('verse_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(default=None)),
                ('title', models.CharField(max_length=500)),
                ('verse', models.CharField(default='Hello', max_length=1000)),
                ('verse_name', models.CharField(default='Hello', max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
    ]
